### ISSUE TITLE
Unknown function: ingo#err#Clear

### ISSUE THREAD

**Issue by naseer** [inkarkat/vim-mark#1]
I'm getting this error when using mark.vim on marking a word (installed with vim-plug)

Error detected while processing function mark#MarkCurrentWord[13]..mark#DoMark:
line    1:
E117: Unknown function: ingo#err#Clear
mark-5/\<nmap\>

**Comment by inkarkat** [comment]
You also need to install the [ingo-library plugin](http://www.vim.org/scripts/script.php?script_id=4433) (or via [GitHub](https://github.com/inkarkat/vim-ingo-library)). It's listed in the [dependencies](https://github.com/inkarkat/vim-mark#dependencies).

**Comment by naseer** [comment]
Thanks - that worked, and thanks for the great plugin!
