### ISSUE TITLE
Remove the fork lable so that everyone can find it easily by searching 'vim-mark'?

### ISSUE THREAD

**Issue by Yggdroot** [inkarkat/vim-mark#18]

**Comment by inkarkat** [comment]
Apparently, it's not so easy. To do this without losing existing issues, one has to contact GitHub support, and ask them to do it.

When I do a Google search for "vim-mark", the link to this repo is the third one, and the fourth one is to its vim.org plugin page (which also links to here). (The first two results are on related Vim Tips Wiki pages.)
