### ISSUE TITLE
Installation instructions incomplete

### ISSUE THREAD

**Issue by PlasmaHH** [inkarkat/vim-mark#19]
while the changelog later mentions it, the installation section just tells to git clone this repo, while you need that ingo library repo too. It should be eplicitly mentioned in the installation section that it is needed.

**Comment by inkarkat** [comment]
It's not just in the changelog, the `DEPENDENCIES` paragraph that [immediately follows](https://github.com/inkarkat/vim-mark/blob/c18e474e1775aed7073099342384ed322aa6f1f7/doc/mark.txt#L325-L329) the `INSTALLATION` section also mentions it.

I have the feeling that no matter how prominent this note is made, there will always be some people who don't read it. And even though multiple such (closed) issues now already exist here, these people are also prone to not finding them and opening new issues instead. That's life :-)
