### ISSUE TITLE
issue when using base16 theme

### ISSUE THREAD

**Issue by damnskippy** [inkarkat/vim-mark#21]
This might be potentially be an issue with base16 themes (https://github.com/chriskempson/base16-vim) or likely something in my setup/environment, but I wanted to run this by you just in case and ask for help in debugging.
The problem is when I use one of the base16-themes (set in my vimrc), then setting a mark does not do any highlighting.  There are otherwise no errors/messages, and if I toggle the mark at this point, the status message indicates the mark is actually getting cleared.  However visually the selected word is not marked with coloring at all, even though the mark is getting set and cleared.
This happens only when I use the base16 theme.  No issues at all with any other theme.

However I noticed the following which may offer some clues, maybe.  After loading with base16 theme, if I do a `MarkPalette extended` (or any other palette) then setting the marks works just fine.  The marks that I had set previously also now get highlighted (colored). 
The problem also clears up if I load another vim colorscheme, and then load the base16 theme back again.

It's as if something somewhere is not getting initialized correctly or is getting overwritten during startup.  Does this ring any bell for you?

Again this problem happens only when using a base16 theme, every other color theme I've possibly used has never exhibited this issue.

I'm using the latest vim sources and latest source of both base16 and vim-mark sources.

Thank you.

**Comment by inkarkat** [comment]
Colorschemes clear any existing highlightings, and that includes those from the Mark plugin. It hooks into colorscheme changes (via [autocmd](https://github.com/inkarkat/vim-mark/blob/ea9886d8ca26fa2389ec741f9d2d2fa7b02f042d/plugin/mark.vim#L115), and as you report, this usually works pretty well.

I had a quick look at the _base16-vim_ colorscheme (actually, there seems to be a whole, auto-generated family of schemes). It does many weird things (that normal colorschemes don't do), but I couldn't find something that would cause these problems. From what you report, this indeed looks like wrong initialization order.

In general, the `:colorscheme` should be set _before_ the plugins load; you can verify with `:scriptnames`. If you let Vim load the plugins in the normal order, this should just work, but some plugin managers explicitly load plugins, triggered from the `.vimrc`, and then the order can matter.

If you can't solve the problem with reordering, a workaround would be to reinitialize the Mark palette later; the [`:help VimEnter`](https://vimhelp.appspot.com/autocmd.txt.html#VimEnter) would be a good candidate, e.g.

    :autocmd VimEnter * doautocmd ColorScheme

or more directly

    :autocmd VimEnter * MarkPalette extended

I hope some of this helps. It may be worthwhile to report this to the base16-vim project as well; they may have their reasons for defining the colorscheme in an usual way, but it's likely that some of that is causing this integration problem.

**Comment by damnskippy** [comment]
Thanks.  The script ordering seems fine.  For now I decided to work around by hooking `MarkPalette` to `autocmd FocusGained` (even setting this via `VimEnter` wasn't enough).
Thanks again.

**Comment by inkarkat** [comment]
If you want to do more troubleshooting, you can capture a full log of a Vim session with `vim -V20vimlog`. After quitting Vim, examine the `vimlog` log file. There has to be a `:highlight clear` somewhere, and then there are the `:highlight` commands from the Mark plugin. If there's a / another `:highlight clear` after the plugin initialization, you've found the culprit, and only have to go back in time to see where and by what it got triggered.
