### ISSUE TITLE
Update marks failed.

### ISSUE THREAD

**Issue by gryf** [inkarkat/vim-mark#22]
I've got error on refreshing marks:
```
Error detected while processing function mark#UpdateScope[7]..mark#UpdateMark:                                                                                                                               
line    2:                                                                                                                                                                                                   
E117: Unknown function: ingo#actions#EvaluateOrFunc                                                                                                                                                          
E15: Invalid expression: ingo#actions#EvaluateOrFunc(l:Predicate) 
```
Which is caused by ` ingo#actions#EvaluateOrFunc` which doesn't exists.

**Comment by inkarkat** [comment]
You also need to install (or update, if you have a really old version) the [ingo-library plugin](http://www.vim.org/scripts/script.php?script_id=4433) (or via [GitHub](https://github.com/inkarkat/vim-ingo-library)). It's listed in the [dependencies](https://github.com/inkarkat/vim-mark#dependencies). This library contains common autoload functions that are used by almost all of my plugins; it avoids code duplication and versioning issues.

**Comment by gryf** [comment]
Ah, OK, my bad.
This wasn't the case couple of months ago, isn't it? In case of vim plugins, I'd rather avoid plugins, which have dependences on any other libs, especially, where lib contain like over 200 different helpers, while in the plugin uses just a few of them.

**Comment by inkarkat** [comment]
The dependency exists since version 3.0.0, released last September. Except for a tiny bit of disk space, you don't need to be concerned about all the other, so far unused modules. More information can be found in #10. User ayuanx started a [fork that manually includes the dependencies](https://github.com/ayuanx/vim-mark-standalone) in the plugin itself, but he's already behind with updating it.
