### ISSUE TITLE
error at vim open

### ISSUE THREAD

**Issue by jreybert** [inkarkat/vim-mark#23]
When I open vim, mark plugin seems to have issue to load its history.

Whatever the file I open (even starting vim withotu any file), I get the following error:
```
Error detected while processing function <SNR>52_AutoLoadMarks:
line    1:
E691: Can only compare List with List
Error detected while processing function <SNR>52_AutoLoadMarks:
line    1:
E15: Invalid expression: g:mwAutoLoadMarks && exists('g:MARK_MARKS') && g:MARK_MARKS !=# '[]'
```

I tried to wipe the `.nvinfo` file, I still the same error.

* nvim version: `NVIM v0.3.2-1041-g05d8a46ec`
* mark version: `7d885bd Documentation: Minor: Use :set ^= instead of += for 'viminfo'`
* ingo-library version: `13674a6 Add ingo#collections#SortOnOneAttribute(), ingo#collections#PrioritySort(), and ingo#collections#SortOnTwoAttributes()`

**Comment by inkarkat** [comment]
Thanks for trying out the latest development snapshots! That was a regression that could only been seen when the automatic loading of marks is enabled.

**Comment by jreybert** [comment]
Thanks to plugin managers which are updating on master by default ;-)

And thanks for this plugin, I use it extensively every day! My source code always looks like a unicorn puked on it.
