### ISSUE TITLE
neovim: "invalid address type value: other"

### ISSUE THREAD

**Issue by rgreenblatt** [inkarkat/vim-mark#25]
This is caused by 6016b28. I guess neovim doesn't have support for -addr=other?
I can't find -addr=other in the docs for command at least.

**Comment by sbrahul** [comment]
I don't have neovim, but have vim 7.4.1689.
I also see the same error.

**Comment by inkarkat** [comment]
This should be fixed (for Vim) by 92a88871b873c3af47fd8383123c66966fdf4c3e; my nightly automated test run caught this regression as well.

@rgreenblatt I don't explicitly consider nor test Neovim compatibility; my plugins are written for Vim. If a plugin can be made to work on Neovim with trivial changes, I wouldn't mind including them, but anything more involved should in my opinion be filed as a compatibility bug against Neovim (as its homepage proclaims: _Fully compatible with Vim's editing model and the Vimscript language._)

PS: Unless you want to participate in feature development and alpha testing, I would recommend that you switch from _master_ to the _stable_ branch; this way, you'll only update to released versions that are (hopefully) better tested and documented.
