### ISSUE TITLE
Installation should mention dependency on vim-ingo-library

### ISSUE THREAD

**Issue by theimpostor** [inkarkat/vim-mark#27]
I installed this plugin with vim-plug, upon first usage of <leader>m I got a bunch of undefined function errors. After adding the vim-ingo-library these errors resolved. I would suggest adding a note in the readme installation section that https://github.com/inkarkat/vim-ingo-library should be installed along with this one.

Thanks for the awesome plugin.

**Comment by inkarkat** [comment]
A note and link to the ingo-library plugin page on vim.org (which then links back to GitHub) [already exists under the dependencies subsection of the installation section](https://github.com/inkarkat/vim-mark/blob/master/README.md#L320-L321). Don't feel bad, there's a lot of text in the readme (especially for this plugin), many people (including me) often just skim the text, and you're not the first who encountered this. I think no matter where you put it (and how prominent it appears), someone will always overlook it. However, I'm going to add a GitHub issue template to all of my plugins that explicitly asks the user to confirm what the dependency has been installed; that might prevent some issues from being opened.
