### ISSUE TITLE
for a multi-line mark, * on cursor degrades to vim search

### ISSUE THREAD

**Issue by ericsunplus** [inkarkat/vim-mark#30]
**Describe the bug**

When I specify a multi line regular expression for match, use `<Leader>/` is fine for next occurence, but after the cursor is on highlight, `*` don't jump to next mark, instead it becomes vim normal `*` which simply search for the word under cursor

**How to Reproduce**
For example, using the following text
```text
This is a test
for inkarkat vim-mark
I want to mark a pattern
in multiple lines
the cursor is on the search
but * becomes vim superstar for normal search
```

1. `:Mark /.*vim.*\n.*pattern/`, this will mark line 2 and line 3
2. Using `<Leader>/` to jump to the first(only) Mark match
3. With the cursor on line 2, use `*`, this time it searches for `for` under cursor instead for the next mark occurrence

**Environment**
 - revision _ae3370b4_ from the master branch
 - Vim version _8.2.960_
 - OS: (_Windows 10 1803_)
 - Install method: (Plugin manager _Vundle_)

**Comment by inkarkat** [comment]
Navigating to marks was only supported from the first line, as [this comment](https://github.com/inkarkat/vim-mark/blob/f3686933214d5f4da6c773bd448841ffe8dbe5a5/autoload/mark.vim#L519-L520) shows:

>  The mark can include the trailing newline character that concludes the line,
>  but marks that span multiple lines are not supported.

However, by reusing a function from the [ingo-library plugin](http://www.vim.org/scripts/script.php?script_id=4433) (or via [GitHub](https://github.com/inkarkat/vim-ingo-library) (the latest development snapshot is needed), this can be made to work.

Thanks for the report; the _how to reproduce_ steps helped a lot to quickly see the problem!

**Comment by ericsunplus** [comment]
Just sync `vim-ingo-library` and `vim-mark` to latest on their master branch and the problem get solved. Thank you for the great plugin and the quick problem solving, really help me a lot in my coding.
