### ISSUE TITLE
Window with WinBar gets smaller every time add or delete mark

### ISSUE THREAD

**Issue by fedorenchik** [inkarkat/vim-mark#34]
**Describe the bug**

Window with `WinBar` gets smaller every time add or delete mark.
This happens in other window, that is, window where to add mark, and window with `WinBar` should be 2 different windows. And their location is: window with text above, window with `WinBar` directly below window with text where add / delete mark happens. 

If there's no `WinBar`, this bug does not happen.

**How to Reproduce**

1. Open `vim` or `gvim`
2. `^Ws` to split
3. Focus 2nd window
3. `nnoremenu WinBar.test1 1.10 :anything`
4. `nnoremenu WinBar.test2 1.20 :anything`
5. Focus 1st window
5. use `<Leader>m` to mark & unmark any text
6. observe splitted window gets smaller everytime mark or unmark happens.

**Expected Behavior**

Windows sizes don't change.

**Environment**
 - Plugin version: revision _4494d26_ from the master branch
 - Dependency versions (e.g. [ingo-library plugin](https://github.com/inkarkat/vim-ingo-library)): revision _76bc5d1_ from master branch
 - Vim version (e.g. _8.2.2489_)
 - result of `vim --version`:
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 10 2021 11:11:17)
Included patches: 1-2489
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
+autoservername    +folding           +multi_byte        +termguicolors
+balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
+browse            -gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              -perl              +title
+clientserver      +job               +persistent_undo   +toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         +python3/dyn       +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua/dyn           -ruby              +wildmenu
+dialog_con_gui    +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       +X11
+dnd               +mouse             +sound             -xfontset
-ebcdic            +mouseshape        +spell             +xim
+emacs_tags        +mouse_dec         +startuptime       +xpm
+eval              +mouse_gpm         +statusline        +xsmp_interact
+ex_extra          -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/home/leonid/.local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/lzo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cloudproviders -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/at-spi-2.0 -pthread -g -O2 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -L/usr/local/lib -Wl,--as-needed -o vim -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -lelf -lcanberra -lacl -lattr -lgpm -ldl
```
 - OS: Manjaro KDE
 - Install method: GitHub clone as pack plugin
 - Sometimes makes vim crash (maybe when terminal window is opened)

**Comment by fedorenchik** [comment]
Update: this bug does not make vim crash.

Crash is other vim bug, not related to this one: vim/vim#7890

**Comment by inkarkat** [comment]
The plugin has to temporarily visit every window of the tab page in order to update the highlighting there. It does use [`winrestcmd()`](https://vimhelp.appspot.com/eval.txt.html#winrestcmd%28%29) in order to restore the original layout, but other plugins may not play well with that.

I've now changed the implementation to use [`win_execute()`](https://vimhelp.appspot.com/eval.txt.html#win_execute%28%29) - this has virtually no side effects that need to be undone. I hope that this solves the issue. (If not, I'm out of ideas about what to do differently - also because I've never experienced such issues myself.)

For compatibility, the implementation falls back to the old algorithm (that uses `:windo`); this is encapsulated in [ingo-library](https://github.com/inkarkat/vim-ingo-library), so that one needs to be updated as well.

**Comment by fedorenchik** [comment]
It is fixed. Thank you.
