### ISSUE TITLE
Ability to use n/N to perform `MarkSearchAnyNext`/`MarkSearchAnyPrev`

### ISSUE THREAD

**Issue by dkasak** [inkarkat/vim-mark#39]
**Motivation**

I want to use vim's regular `n` and `N` keys to cycle forward/backward through any mark *if there is any mark defined*. Otherwise, I'd like `n` and `N` to perform their usual function.

**Request and Purpose**

If there are any marks defined, I'd like `n` and `N` to perform `MarkSearchAnyNext` and `MarkSearchAnyPrev`, respectively. If there are no marks, or all the marks are disabled, I'd like `n` and `N` to fall back to their usual function.

This should obviously be configurable as not all users will want this.

**Alternatives**

Alternatively, adding, removing or toggling marks could update vim's last search pattern. The downside of this solution is that you lose the ability to highlight each mark in a separate colour (at least until you do `:nohl`).

**Comment by inkarkat** [comment]
Everybody has their own approach to searching, and I can see how the fallback to the default search pattern could be useful.

Most of the functionality for implementing this is already present; I just had to expose the mark enablement flag.

There are now two new mappings; by default these are not assigned to any keys, but you can define your own mapping (e.g. overriding the built-in `n` / `N` as you've suggested, or using any other keys for them) by putting this into your `~/.vimrc`:

    nmap n <Plug>MarkSearchAnyOrDefaultNext
    nmap N <Plug>MarkSearchAnyOrDefaultPrev

Thanks for the suggestion, and happy Vimming!

**Comment by dkasak** [comment]
Thank you so much for implementing this so quickly! I really appreciate this excellent plugin.
