### ISSUE TITLE
How to delete the slot saved by MarkSave 

### ISSUE THREAD

**Issue by ruleizhou** [inkarkat/vim-mark#42]
**Frequent Issues**

* **E117: Unknown function: ingo#...**: Have you installed the [ingo-library plugin](http://www.vim.org/scripts/script.php?script_id=4433) (or via [GitHub](https://github.com/inkarkat/vim-ingo-library)) as well, as documented in the _dependencies_ section of the readme and plugin help?
* **Sudden problems after updating**: Did you check out the default _master_ branch? Unless you want to participate in feature development and alpha testing, I would recommend that you switch from _master_ to the _stable_ branch; this way, you'll only update to released versions that are (hopefully) better tested and documented.
* **Neovim**: I don't explicitly consider nor test Neovim compatibility; my plugins are written for Vim. If a plugin can be made to work on Neovim with trivial changes, I wouldn't mind including them, but anything more involved should in my opinion be filed as a compatibility bug against Neovim (as its homepage proclaims: _Fully compatible with Vim's editing model and the Vimscript language._)

**Describe the bug**

_A clear and concise description of what the bug is._

**How to Reproduce**

_Detailed steps to reproduce the behavior._

**Expected Behavior**

_A clear and concise description of what you expected to happen._

**Environment**
 - Plugin version (e.g. stable version _1.10_) / revision _a1b2c3d4_ from the master branch
 - Dependency versions (e.g. [ingo-library plugin](https://github.com/inkarkat/vim-ingo-library), or external tool versions)
 - Vim version (e.g. _8.1.1234_) Or paste the result of `vim --version`.
 - OS: (e.g. _Ubuntu 18.04_, _Windows 10 1809_, _macOS 10.14_)
 - Install method: (e.g. manually via Vimball or ZIP file, GitHub clone as pack plugin, Plugin manager _NAME_)
 - Other plugins / additional context if you think this could be important

**Comment by inkarkat** [comment]
`:MarkSave` will clear the persisted marks if no marks are currently defined. So the combination of `:MarkClear` and `:MarkSave` will do it.

If you want to keep the marks, just delete them, you can directly `:unlet g:MARK_MARKS` (or `:unlet g:{slot}` if you've used a named slot).
