### ISSUE TITLE
Sourcing .vimrc file breaks highlighting

### ISSUE THREAD

**Issue by klew** [inkarkat/vim-mark#44]
When I manually source .vimrc file (i.e. to load new settings), it make all highlighting disappear.

**How to Reproduce**

I use VIM 9.0 and plugin is installed via Vundle.
1. Open gvim
2. open .vimrc: :e $MYVIMRS
3. I highlight some words by using leader-m (everything works fine)
4. Source .vimrc: :so %
5. Highlighting disappears and leader-m has no visual effect anymore. I see echo'ed commands, i.e. mark-3 cleared, etc. No error messages are visible.

I have to quit vim and start it again to make it work.

**Expected Behavior**

Sourcing .vimrc file should have no impact on plugin functionality.

**Environment**
 - Plugin version: latest revision 892740366 from the master branch
 - Dependency versions (latest ingo-library revision [cb7c672](https://github.com/inkarkat/vim-ingo-library/commit/cb7c6728608e3c727e0620582f0b0becd8ce28f3))
 - Vim version:
 VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jan 19 2023 10:45:53)
Included patches: 1-1221
 - OS: (Ubuntu 22.10)
 - Install method: (Plugin manager Vundle)

**Comment by inkarkat** [comment]
The plugin redefines its highlight definitions by hooking into the `ColorScheme` event; unfortunately that wasn't in a plugin group but globally scoped, so if you have a `:autocmd! ColorScheme ...` in your `.vimrc` it would get cleared, and the mark colors would be gone.

This should now be fixed; however, you could still potentially do other stuff in the `.vimrc` that breaks the plugin when it's reloaded, but hey, that's not a common use case, anyway, and a complete restart of Vim isn't that tragic.

**Comment by klew** [comment]
Thanks for quick fix. It works now!

I don't have any autocmd on ColorScheme, so probably something elso was messing it up.

**Comment by inkarkat** [comment]
Thanks for the feedback; I'm glad it helped. The culprit doesn't have to be in the vimrc itself; it could also be another plugin.
