### ISSUE TITLE
mark word issue

### ISSUE THREAD

**Issue by Ywang153** [inkarkat/vim-mark#7]
hi, I encountered the below issue, Could you please help to have a look? Thanks.

Error detected while processing function mark#MarkCurrentWord[13]..mark#DoMark:

:ver
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
Included patches: 1-1453

Distro: Ubuntu 18.04 LTS

**Comment by inkarkat** [comment]
The (full) actual error message would have been helpful :-)

I guess it's this: You also need to install the [ingo-library plugin](http://www.vim.org/scripts/script.php?script_id=4433) (or via [GitHub](https://github.com/inkarkat/vim-ingo-library)). It's listed in the [dependencies](https://github.com/inkarkat/vim-mark#dependencies). This library contains common autoload functions that are used by almost all of my plugins; it avoids code duplication and versioning issues.

If not, please add more details and reopen!
